=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

module ConvoyApi
  VERSION = '1.0.0'
end
