=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class AuthRoleType
    RoleInstanceAdmin = "instance_admin".freeze
    RoleOrganisationAdmin = "organisation_admin".freeze
    RoleBillingAdmin = "billing_admin".freeze
    RoleProjectAdmin = "project_admin".freeze
    RoleProjectViewer = "project_viewer".freeze
    RoleAPI = "api".freeze

    def self.all_vars
      @all_vars ||= [RoleInstanceAdmin, RoleOrganisationAdmin, RoleBillingAdmin, RoleProjectAdmin, RoleProjectViewer, RoleAPI].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AuthRoleType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AuthRoleType"
    end
  end
end
