=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class DatastoreMetadata < ApiModelBase
    # Data to be sent to endpoint.
    attr_accessor :data

    attr_accessor :interval_seconds

    attr_accessor :max_retry_seconds

    attr_accessor :next_send_time

    # NumTrials: number of times we have tried to deliver this Event to an application
    attr_accessor :num_trials

    attr_accessor :raw

    attr_accessor :retry_limit

    attr_accessor :strategy

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'data' => :'data',
        :'interval_seconds' => :'interval_seconds',
        :'max_retry_seconds' => :'max_retry_seconds',
        :'next_send_time' => :'next_send_time',
        :'num_trials' => :'num_trials',
        :'raw' => :'raw',
        :'retry_limit' => :'retry_limit',
        :'strategy' => :'strategy'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'data' => :'Hash<String, Object>',
        :'interval_seconds' => :'Integer',
        :'max_retry_seconds' => :'Integer',
        :'next_send_time' => :'String',
        :'num_trials' => :'Integer',
        :'raw' => :'String',
        :'retry_limit' => :'Integer',
        :'strategy' => :'DatastoreStrategyProvider'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'data',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::DatastoreMetadata` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::DatastoreMetadata`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'data')
        if (value = attributes[:'data']).is_a?(Hash)
          self.data = value
        end
      end

      if attributes.key?(:'interval_seconds')
        self.interval_seconds = attributes[:'interval_seconds']
      end

      if attributes.key?(:'max_retry_seconds')
        self.max_retry_seconds = attributes[:'max_retry_seconds']
      end

      if attributes.key?(:'next_send_time')
        self.next_send_time = attributes[:'next_send_time']
      end

      if attributes.key?(:'num_trials')
        self.num_trials = attributes[:'num_trials']
      end

      if attributes.key?(:'raw')
        self.raw = attributes[:'raw']
      end

      if attributes.key?(:'retry_limit')
        self.retry_limit = attributes[:'retry_limit']
      end

      if attributes.key?(:'strategy')
        self.strategy = attributes[:'strategy']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          data == o.data &&
          interval_seconds == o.interval_seconds &&
          max_retry_seconds == o.max_retry_seconds &&
          next_send_time == o.next_send_time &&
          num_trials == o.num_trials &&
          raw == o.raw &&
          retry_limit == o.retry_limit &&
          strategy == o.strategy
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [data, interval_seconds, max_retry_seconds, next_send_time, num_trials, raw, retry_limit, strategy].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
