=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class DatastorePortalLinkResponse < ApiModelBase
    attr_accessor :auth_key

    attr_accessor :auth_type

    attr_accessor :can_manage_endpoint

    attr_accessor :created_at

    attr_accessor :deleted_at

    attr_accessor :endpoint_count

    attr_accessor :endpoints

    attr_accessor :endpoints_metadata

    attr_accessor :name

    attr_accessor :owner_id

    attr_accessor :project_id

    attr_accessor :token

    attr_accessor :uid

    attr_accessor :updated_at

    attr_accessor :url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'auth_key' => :'auth_key',
        :'auth_type' => :'auth_type',
        :'can_manage_endpoint' => :'can_manage_endpoint',
        :'created_at' => :'created_at',
        :'deleted_at' => :'deleted_at',
        :'endpoint_count' => :'endpoint_count',
        :'endpoints' => :'endpoints',
        :'endpoints_metadata' => :'endpoints_metadata',
        :'name' => :'name',
        :'owner_id' => :'owner_id',
        :'project_id' => :'project_id',
        :'token' => :'token',
        :'uid' => :'uid',
        :'updated_at' => :'updated_at',
        :'url' => :'url'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'auth_key' => :'String',
        :'auth_type' => :'DatastorePortalAuthType',
        :'can_manage_endpoint' => :'Boolean',
        :'created_at' => :'String',
        :'deleted_at' => :'String',
        :'endpoint_count' => :'Integer',
        :'endpoints' => :'Array<String>',
        :'endpoints_metadata' => :'Array<DatastoreEndpoint>',
        :'name' => :'String',
        :'owner_id' => :'String',
        :'project_id' => :'String',
        :'token' => :'String',
        :'uid' => :'String',
        :'updated_at' => :'String',
        :'url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'deleted_at',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::DatastorePortalLinkResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::DatastorePortalLinkResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'auth_key')
        self.auth_key = attributes[:'auth_key']
      end

      if attributes.key?(:'auth_type')
        self.auth_type = attributes[:'auth_type']
      end

      if attributes.key?(:'can_manage_endpoint')
        self.can_manage_endpoint = attributes[:'can_manage_endpoint']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'deleted_at')
        self.deleted_at = attributes[:'deleted_at']
      end

      if attributes.key?(:'endpoint_count')
        self.endpoint_count = attributes[:'endpoint_count']
      end

      if attributes.key?(:'endpoints')
        if (value = attributes[:'endpoints']).is_a?(Array)
          self.endpoints = value
        end
      end

      if attributes.key?(:'endpoints_metadata')
        if (value = attributes[:'endpoints_metadata']).is_a?(Array)
          self.endpoints_metadata = value
        end
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'owner_id')
        self.owner_id = attributes[:'owner_id']
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'token')
        self.token = attributes[:'token']
      end

      if attributes.key?(:'uid')
        self.uid = attributes[:'uid']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          auth_key == o.auth_key &&
          auth_type == o.auth_type &&
          can_manage_endpoint == o.can_manage_endpoint &&
          created_at == o.created_at &&
          deleted_at == o.deleted_at &&
          endpoint_count == o.endpoint_count &&
          endpoints == o.endpoints &&
          endpoints_metadata == o.endpoints_metadata &&
          name == o.name &&
          owner_id == o.owner_id &&
          project_id == o.project_id &&
          token == o.token &&
          uid == o.uid &&
          updated_at == o.updated_at &&
          url == o.url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [auth_key, auth_type, can_manage_endpoint, created_at, deleted_at, endpoint_count, endpoints, endpoints_metadata, name, owner_id, project_id, token, uid, updated_at, url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
