=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class DatastoreSource < ApiModelBase
    attr_accessor :body_function

    attr_accessor :created_at

    attr_accessor :custom_response

    attr_accessor :deleted_at

    attr_accessor :event_type_location

    attr_accessor :forward_headers

    attr_accessor :header_function

    attr_accessor :idempotency_keys

    attr_accessor :is_disabled

    attr_accessor :mask_id

    attr_accessor :name

    attr_accessor :project_id

    attr_accessor :provider

    attr_accessor :provider_config

    attr_accessor :pub_sub

    attr_accessor :type

    attr_accessor :uid

    attr_accessor :updated_at

    attr_accessor :url

    attr_accessor :verifier

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'body_function' => :'body_function',
        :'created_at' => :'created_at',
        :'custom_response' => :'custom_response',
        :'deleted_at' => :'deleted_at',
        :'event_type_location' => :'event_type_location',
        :'forward_headers' => :'forward_headers',
        :'header_function' => :'header_function',
        :'idempotency_keys' => :'idempotency_keys',
        :'is_disabled' => :'is_disabled',
        :'mask_id' => :'mask_id',
        :'name' => :'name',
        :'project_id' => :'project_id',
        :'provider' => :'provider',
        :'provider_config' => :'provider_config',
        :'pub_sub' => :'pub_sub',
        :'type' => :'type',
        :'uid' => :'uid',
        :'updated_at' => :'updated_at',
        :'url' => :'url',
        :'verifier' => :'verifier'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'body_function' => :'String',
        :'created_at' => :'String',
        :'custom_response' => :'DatastoreCustomResponse',
        :'deleted_at' => :'String',
        :'event_type_location' => :'String',
        :'forward_headers' => :'Array<String>',
        :'header_function' => :'String',
        :'idempotency_keys' => :'Array<String>',
        :'is_disabled' => :'Boolean',
        :'mask_id' => :'String',
        :'name' => :'String',
        :'project_id' => :'String',
        :'provider' => :'DatastoreSourceProvider',
        :'provider_config' => :'DatastoreProviderConfig',
        :'pub_sub' => :'DatastorePubSubConfig',
        :'type' => :'DatastoreSourceType',
        :'uid' => :'String',
        :'updated_at' => :'String',
        :'url' => :'String',
        :'verifier' => :'DatastoreVerifierConfig'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'body_function',
        :'deleted_at',
        :'header_function',
        :'provider_config',
        :'pub_sub',
        :'verifier'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::DatastoreSource` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::DatastoreSource`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'body_function')
        self.body_function = attributes[:'body_function']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'custom_response')
        self.custom_response = attributes[:'custom_response']
      end

      if attributes.key?(:'deleted_at')
        self.deleted_at = attributes[:'deleted_at']
      end

      if attributes.key?(:'event_type_location')
        self.event_type_location = attributes[:'event_type_location']
      end

      if attributes.key?(:'forward_headers')
        if (value = attributes[:'forward_headers']).is_a?(Array)
          self.forward_headers = value
        end
      end

      if attributes.key?(:'header_function')
        self.header_function = attributes[:'header_function']
      end

      if attributes.key?(:'idempotency_keys')
        if (value = attributes[:'idempotency_keys']).is_a?(Array)
          self.idempotency_keys = value
        end
      end

      if attributes.key?(:'is_disabled')
        self.is_disabled = attributes[:'is_disabled']
      end

      if attributes.key?(:'mask_id')
        self.mask_id = attributes[:'mask_id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'provider')
        self.provider = attributes[:'provider']
      end

      if attributes.key?(:'provider_config')
        self.provider_config = attributes[:'provider_config']
      end

      if attributes.key?(:'pub_sub')
        self.pub_sub = attributes[:'pub_sub']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'uid')
        self.uid = attributes[:'uid']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'verifier')
        self.verifier = attributes[:'verifier']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          body_function == o.body_function &&
          created_at == o.created_at &&
          custom_response == o.custom_response &&
          deleted_at == o.deleted_at &&
          event_type_location == o.event_type_location &&
          forward_headers == o.forward_headers &&
          header_function == o.header_function &&
          idempotency_keys == o.idempotency_keys &&
          is_disabled == o.is_disabled &&
          mask_id == o.mask_id &&
          name == o.name &&
          project_id == o.project_id &&
          provider == o.provider &&
          provider_config == o.provider_config &&
          pub_sub == o.pub_sub &&
          type == o.type &&
          uid == o.uid &&
          updated_at == o.updated_at &&
          url == o.url &&
          verifier == o.verifier
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [body_function, created_at, custom_response, deleted_at, event_type_location, forward_headers, header_function, idempotency_keys, is_disabled, mask_id, name, project_id, provider, provider_config, pub_sub, type, uid, updated_at, url, verifier].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
