=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class DatastoreCircuitBreakerConfiguration < ApiModelBase
    attr_accessor :consecutive_failure_threshold

    attr_accessor :error_timeout

    attr_accessor :failure_threshold

    attr_accessor :minimum_request_count

    attr_accessor :observability_window

    attr_accessor :sample_rate

    attr_accessor :success_threshold

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'consecutive_failure_threshold' => :'consecutive_failure_threshold',
        :'error_timeout' => :'error_timeout',
        :'failure_threshold' => :'failure_threshold',
        :'minimum_request_count' => :'minimum_request_count',
        :'observability_window' => :'observability_window',
        :'sample_rate' => :'sample_rate',
        :'success_threshold' => :'success_threshold'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'consecutive_failure_threshold' => :'Integer',
        :'error_timeout' => :'Integer',
        :'failure_threshold' => :'Integer',
        :'minimum_request_count' => :'Integer',
        :'observability_window' => :'Integer',
        :'sample_rate' => :'Integer',
        :'success_threshold' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::DatastoreCircuitBreakerConfiguration` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::DatastoreCircuitBreakerConfiguration`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'consecutive_failure_threshold')
        self.consecutive_failure_threshold = attributes[:'consecutive_failure_threshold']
      end

      if attributes.key?(:'error_timeout')
        self.error_timeout = attributes[:'error_timeout']
      end

      if attributes.key?(:'failure_threshold')
        self.failure_threshold = attributes[:'failure_threshold']
      end

      if attributes.key?(:'minimum_request_count')
        self.minimum_request_count = attributes[:'minimum_request_count']
      end

      if attributes.key?(:'observability_window')
        self.observability_window = attributes[:'observability_window']
      end

      if attributes.key?(:'sample_rate')
        self.sample_rate = attributes[:'sample_rate']
      end

      if attributes.key?(:'success_threshold')
        self.success_threshold = attributes[:'success_threshold']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          consecutive_failure_threshold == o.consecutive_failure_threshold &&
          error_timeout == o.error_timeout &&
          failure_threshold == o.failure_threshold &&
          minimum_request_count == o.minimum_request_count &&
          observability_window == o.observability_window &&
          sample_rate == o.sample_rate &&
          success_threshold == o.success_threshold
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [consecutive_failure_threshold, error_timeout, failure_threshold, minimum_request_count, observability_window, sample_rate, success_threshold].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
