=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class DatastoreProjectConfig < ApiModelBase
    attr_accessor :add_event_id_trace_headers

    attr_accessor :circuit_breaker

    attr_accessor :disable_endpoint

    attr_accessor :max_payload_read_size

    attr_accessor :meta_event

    attr_accessor :multiple_endpoint_subscriptions

    attr_accessor :ratelimit

    attr_accessor :replay_attacks_prevention_enabled

    attr_accessor :request_id_header

    attr_accessor :search_policy

    attr_accessor :signature

    attr_accessor :ssl

    attr_accessor :strategy

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'add_event_id_trace_headers' => :'add_event_id_trace_headers',
        :'circuit_breaker' => :'circuit_breaker',
        :'disable_endpoint' => :'disable_endpoint',
        :'max_payload_read_size' => :'max_payload_read_size',
        :'meta_event' => :'meta_event',
        :'multiple_endpoint_subscriptions' => :'multiple_endpoint_subscriptions',
        :'ratelimit' => :'ratelimit',
        :'replay_attacks_prevention_enabled' => :'replay_attacks_prevention_enabled',
        :'request_id_header' => :'request_id_header',
        :'search_policy' => :'search_policy',
        :'signature' => :'signature',
        :'ssl' => :'ssl',
        :'strategy' => :'strategy'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'add_event_id_trace_headers' => :'Boolean',
        :'circuit_breaker' => :'DatastoreCircuitBreakerConfiguration',
        :'disable_endpoint' => :'Boolean',
        :'max_payload_read_size' => :'Integer',
        :'meta_event' => :'DatastoreMetaEventConfiguration',
        :'multiple_endpoint_subscriptions' => :'Boolean',
        :'ratelimit' => :'DatastoreRateLimitConfiguration',
        :'replay_attacks_prevention_enabled' => :'Boolean',
        :'request_id_header' => :'ConfigRequestIDHeaderProvider',
        :'search_policy' => :'String',
        :'signature' => :'DatastoreSignatureConfiguration',
        :'ssl' => :'DatastoreSSLConfiguration',
        :'strategy' => :'DatastoreStrategyConfiguration'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::DatastoreProjectConfig` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::DatastoreProjectConfig`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'add_event_id_trace_headers')
        self.add_event_id_trace_headers = attributes[:'add_event_id_trace_headers']
      end

      if attributes.key?(:'circuit_breaker')
        self.circuit_breaker = attributes[:'circuit_breaker']
      end

      if attributes.key?(:'disable_endpoint')
        self.disable_endpoint = attributes[:'disable_endpoint']
      end

      if attributes.key?(:'max_payload_read_size')
        self.max_payload_read_size = attributes[:'max_payload_read_size']
      end

      if attributes.key?(:'meta_event')
        self.meta_event = attributes[:'meta_event']
      end

      if attributes.key?(:'multiple_endpoint_subscriptions')
        self.multiple_endpoint_subscriptions = attributes[:'multiple_endpoint_subscriptions']
      end

      if attributes.key?(:'ratelimit')
        self.ratelimit = attributes[:'ratelimit']
      end

      if attributes.key?(:'replay_attacks_prevention_enabled')
        self.replay_attacks_prevention_enabled = attributes[:'replay_attacks_prevention_enabled']
      end

      if attributes.key?(:'request_id_header')
        self.request_id_header = attributes[:'request_id_header']
      end

      if attributes.key?(:'search_policy')
        self.search_policy = attributes[:'search_policy']
      end

      if attributes.key?(:'signature')
        self.signature = attributes[:'signature']
      end

      if attributes.key?(:'ssl')
        self.ssl = attributes[:'ssl']
      end

      if attributes.key?(:'strategy')
        self.strategy = attributes[:'strategy']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          add_event_id_trace_headers == o.add_event_id_trace_headers &&
          circuit_breaker == o.circuit_breaker &&
          disable_endpoint == o.disable_endpoint &&
          max_payload_read_size == o.max_payload_read_size &&
          meta_event == o.meta_event &&
          multiple_endpoint_subscriptions == o.multiple_endpoint_subscriptions &&
          ratelimit == o.ratelimit &&
          replay_attacks_prevention_enabled == o.replay_attacks_prevention_enabled &&
          request_id_header == o.request_id_header &&
          search_policy == o.search_policy &&
          signature == o.signature &&
          ssl == o.ssl &&
          strategy == o.strategy
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [add_event_id_trace_headers, circuit_breaker, disable_endpoint, max_payload_read_size, meta_event, multiple_endpoint_subscriptions, ratelimit, replay_attacks_prevention_enabled, request_id_header, search_policy, signature, ssl, strategy].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
