=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class DatastoreOAuth2SigningKey < ApiModelBase
    # EC (Elliptic Curve) key fields
    attr_accessor :crv

    # Private key (EC only)
    attr_accessor :d

    # RSA first factor CRT exponent (RSA private key only)
    attr_accessor :dp

    # RSA second factor CRT exponent (RSA private key only)
    attr_accessor :dq

    # RSA public exponent (RSA only)
    attr_accessor :e

    # Key ID
    attr_accessor :kid

    # Key type: \"EC\" or \"RSA\"
    attr_accessor :kty

    # RSA key fields
    attr_accessor :n

    # RSA first prime factor (RSA private key only)
    attr_accessor :p

    # RSA second prime factor (RSA private key only)
    attr_accessor :q

    # RSA first CRT coefficient (RSA private key only)
    attr_accessor :qi

    # X coordinate (EC only)
    attr_accessor :x

    # Y coordinate (EC only)
    attr_accessor :y

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'crv' => :'crv',
        :'d' => :'d',
        :'dp' => :'dp',
        :'dq' => :'dq',
        :'e' => :'e',
        :'kid' => :'kid',
        :'kty' => :'kty',
        :'n' => :'n',
        :'p' => :'p',
        :'q' => :'q',
        :'qi' => :'qi',
        :'x' => :'x',
        :'y' => :'y'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'crv' => :'String',
        :'d' => :'String',
        :'dp' => :'String',
        :'dq' => :'String',
        :'e' => :'String',
        :'kid' => :'String',
        :'kty' => :'String',
        :'n' => :'String',
        :'p' => :'String',
        :'q' => :'String',
        :'qi' => :'String',
        :'x' => :'String',
        :'y' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::DatastoreOAuth2SigningKey` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::DatastoreOAuth2SigningKey`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'crv')
        self.crv = attributes[:'crv']
      end

      if attributes.key?(:'d')
        self.d = attributes[:'d']
      end

      if attributes.key?(:'dp')
        self.dp = attributes[:'dp']
      end

      if attributes.key?(:'dq')
        self.dq = attributes[:'dq']
      end

      if attributes.key?(:'e')
        self.e = attributes[:'e']
      end

      if attributes.key?(:'kid')
        self.kid = attributes[:'kid']
      end

      if attributes.key?(:'kty')
        self.kty = attributes[:'kty']
      end

      if attributes.key?(:'n')
        self.n = attributes[:'n']
      end

      if attributes.key?(:'p')
        self.p = attributes[:'p']
      end

      if attributes.key?(:'q')
        self.q = attributes[:'q']
      end

      if attributes.key?(:'qi')
        self.qi = attributes[:'qi']
      end

      if attributes.key?(:'x')
        self.x = attributes[:'x']
      end

      if attributes.key?(:'y')
        self.y = attributes[:'y']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          crv == o.crv &&
          d == o.d &&
          dp == o.dp &&
          dq == o.dq &&
          e == o.e &&
          kid == o.kid &&
          kty == o.kty &&
          n == o.n &&
          p == o.p &&
          q == o.q &&
          qi == o.qi &&
          x == o.x &&
          y == o.y
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [crv, d, dp, dq, e, kid, kty, n, p, q, qi, x, y].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
