=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class DatastoreOAuth2 < ApiModelBase
    attr_accessor :audience

    attr_accessor :authentication_type

    attr_accessor :client_id

    # Encrypted at rest
    attr_accessor :client_secret

    # Expiry time unit (seconds, milliseconds, minutes, hours)
    attr_accessor :expiry_time_unit

    # Field mapping for flexible token response parsing
    attr_accessor :field_mapping

    attr_accessor :grant_type

    attr_accessor :issuer

    attr_accessor :scope

    attr_accessor :signing_algorithm

    # Encrypted at rest
    attr_accessor :signing_key

    attr_accessor :subject

    attr_accessor :url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'audience' => :'audience',
        :'authentication_type' => :'authentication_type',
        :'client_id' => :'client_id',
        :'client_secret' => :'client_secret',
        :'expiry_time_unit' => :'expiry_time_unit',
        :'field_mapping' => :'field_mapping',
        :'grant_type' => :'grant_type',
        :'issuer' => :'issuer',
        :'scope' => :'scope',
        :'signing_algorithm' => :'signing_algorithm',
        :'signing_key' => :'signing_key',
        :'subject' => :'subject',
        :'url' => :'url'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'audience' => :'String',
        :'authentication_type' => :'DatastoreOAuth2AuthenticationType',
        :'client_id' => :'String',
        :'client_secret' => :'String',
        :'expiry_time_unit' => :'DatastoreOAuth2ExpiryTimeUnit',
        :'field_mapping' => :'DatastoreOAuth2FieldMapping',
        :'grant_type' => :'String',
        :'issuer' => :'String',
        :'scope' => :'String',
        :'signing_algorithm' => :'String',
        :'signing_key' => :'DatastoreOAuth2SigningKey',
        :'subject' => :'String',
        :'url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'field_mapping',
        :'signing_key',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::DatastoreOAuth2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::DatastoreOAuth2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'audience')
        self.audience = attributes[:'audience']
      end

      if attributes.key?(:'authentication_type')
        self.authentication_type = attributes[:'authentication_type']
      end

      if attributes.key?(:'client_id')
        self.client_id = attributes[:'client_id']
      end

      if attributes.key?(:'client_secret')
        self.client_secret = attributes[:'client_secret']
      end

      if attributes.key?(:'expiry_time_unit')
        self.expiry_time_unit = attributes[:'expiry_time_unit']
      end

      if attributes.key?(:'field_mapping')
        self.field_mapping = attributes[:'field_mapping']
      end

      if attributes.key?(:'grant_type')
        self.grant_type = attributes[:'grant_type']
      end

      if attributes.key?(:'issuer')
        self.issuer = attributes[:'issuer']
      end

      if attributes.key?(:'scope')
        self.scope = attributes[:'scope']
      end

      if attributes.key?(:'signing_algorithm')
        self.signing_algorithm = attributes[:'signing_algorithm']
      end

      if attributes.key?(:'signing_key')
        self.signing_key = attributes[:'signing_key']
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          audience == o.audience &&
          authentication_type == o.authentication_type &&
          client_id == o.client_id &&
          client_secret == o.client_secret &&
          expiry_time_unit == o.expiry_time_unit &&
          field_mapping == o.field_mapping &&
          grant_type == o.grant_type &&
          issuer == o.issuer &&
          scope == o.scope &&
          signing_algorithm == o.signing_algorithm &&
          signing_key == o.signing_key &&
          subject == o.subject &&
          url == o.url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [audience, authentication_type, client_id, client_secret, expiry_time_unit, field_mapping, grant_type, issuer, scope, signing_algorithm, signing_key, subject, url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
