=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class DatastoreEndpointAuthenticationType
    APIKeyAuthentication = "api_key".freeze
    OAuth2Authentication = "oauth2".freeze
    BasicAuthentication = "basic_auth".freeze

    def self.all_vars
      @all_vars ||= [APIKeyAuthentication, OAuth2Authentication, BasicAuthentication].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DatastoreEndpointAuthenticationType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DatastoreEndpointAuthenticationType"
    end
  end
end
