=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class DatastoreEndpoint < ApiModelBase
    attr_accessor :advanced_signatures

    attr_accessor :authentication

    # CBState is the circuit breaker state (\"open\", \"half-open\", \"closed\") so the UI can reflect a tripped breaker on the endpoint status. Nil when CB is off/unlicensed or has no sample for this endpoint.
    attr_accessor :cb_state

    attr_accessor :content_type

    attr_accessor :created_at

    attr_accessor :deleted_at

    attr_accessor :description

    attr_accessor :events

    attr_accessor :failure_count

    # FailureRate is the circuit breaker's rolling failure rate for this endpoint. It is a pointer so the API can return null when no rate was computed (circuit breaker feature off, or sampler not running), distinct from a genuine 0%.
    attr_accessor :failure_rate

    attr_accessor :http_timeout

    # mTLS client certificate configuration
    attr_accessor :mtls_client_cert

    attr_accessor :name

    attr_accessor :owner_id

    # PeriodFailureRate is the period failure rate from event_deliveries, (Failure+Retry)/(Success+Failure+Retry). Retry counts as failed-so-far. Nil when the range has no counted deliveries; sibling counts are transient.
    attr_accessor :period_failure_rate

    attr_accessor :project_id

    attr_accessor :rate_limit

    attr_accessor :rate_limit_duration

    attr_accessor :retry_count

    attr_accessor :secrets

    attr_accessor :slack_webhook_url

    attr_accessor :status

    attr_accessor :success_count

    attr_accessor :support_email

    attr_accessor :uid

    attr_accessor :updated_at

    attr_accessor :url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'advanced_signatures' => :'advanced_signatures',
        :'authentication' => :'authentication',
        :'cb_state' => :'cb_state',
        :'content_type' => :'content_type',
        :'created_at' => :'created_at',
        :'deleted_at' => :'deleted_at',
        :'description' => :'description',
        :'events' => :'events',
        :'failure_count' => :'failure_count',
        :'failure_rate' => :'failure_rate',
        :'http_timeout' => :'http_timeout',
        :'mtls_client_cert' => :'mtls_client_cert',
        :'name' => :'name',
        :'owner_id' => :'owner_id',
        :'period_failure_rate' => :'period_failure_rate',
        :'project_id' => :'project_id',
        :'rate_limit' => :'rate_limit',
        :'rate_limit_duration' => :'rate_limit_duration',
        :'retry_count' => :'retry_count',
        :'secrets' => :'secrets',
        :'slack_webhook_url' => :'slack_webhook_url',
        :'status' => :'status',
        :'success_count' => :'success_count',
        :'support_email' => :'support_email',
        :'uid' => :'uid',
        :'updated_at' => :'updated_at',
        :'url' => :'url'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'advanced_signatures' => :'Boolean',
        :'authentication' => :'DatastoreEndpointAuthentication',
        :'cb_state' => :'String',
        :'content_type' => :'String',
        :'created_at' => :'String',
        :'deleted_at' => :'String',
        :'description' => :'String',
        :'events' => :'Integer',
        :'failure_count' => :'Integer',
        :'failure_rate' => :'Float',
        :'http_timeout' => :'Integer',
        :'mtls_client_cert' => :'DatastoreMtlsClientCert',
        :'name' => :'String',
        :'owner_id' => :'String',
        :'period_failure_rate' => :'Float',
        :'project_id' => :'String',
        :'rate_limit' => :'Integer',
        :'rate_limit_duration' => :'Integer',
        :'retry_count' => :'Integer',
        :'secrets' => :'Array<DatastoreSecret>',
        :'slack_webhook_url' => :'String',
        :'status' => :'DatastoreEndpointStatus',
        :'success_count' => :'Integer',
        :'support_email' => :'String',
        :'uid' => :'String',
        :'updated_at' => :'String',
        :'url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::DatastoreEndpoint` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::DatastoreEndpoint`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'advanced_signatures')
        self.advanced_signatures = attributes[:'advanced_signatures']
      end

      if attributes.key?(:'authentication')
        self.authentication = attributes[:'authentication']
      end

      if attributes.key?(:'cb_state')
        self.cb_state = attributes[:'cb_state']
      end

      if attributes.key?(:'content_type')
        self.content_type = attributes[:'content_type']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'deleted_at')
        self.deleted_at = attributes[:'deleted_at']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'events')
        self.events = attributes[:'events']
      end

      if attributes.key?(:'failure_count')
        self.failure_count = attributes[:'failure_count']
      end

      if attributes.key?(:'failure_rate')
        self.failure_rate = attributes[:'failure_rate']
      end

      if attributes.key?(:'http_timeout')
        self.http_timeout = attributes[:'http_timeout']
      end

      if attributes.key?(:'mtls_client_cert')
        self.mtls_client_cert = attributes[:'mtls_client_cert']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'owner_id')
        self.owner_id = attributes[:'owner_id']
      end

      if attributes.key?(:'period_failure_rate')
        self.period_failure_rate = attributes[:'period_failure_rate']
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'rate_limit')
        self.rate_limit = attributes[:'rate_limit']
      end

      if attributes.key?(:'rate_limit_duration')
        self.rate_limit_duration = attributes[:'rate_limit_duration']
      end

      if attributes.key?(:'retry_count')
        self.retry_count = attributes[:'retry_count']
      end

      if attributes.key?(:'secrets')
        if (value = attributes[:'secrets']).is_a?(Array)
          self.secrets = value
        end
      end

      if attributes.key?(:'slack_webhook_url')
        self.slack_webhook_url = attributes[:'slack_webhook_url']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'success_count')
        self.success_count = attributes[:'success_count']
      end

      if attributes.key?(:'support_email')
        self.support_email = attributes[:'support_email']
      end

      if attributes.key?(:'uid')
        self.uid = attributes[:'uid']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          advanced_signatures == o.advanced_signatures &&
          authentication == o.authentication &&
          cb_state == o.cb_state &&
          content_type == o.content_type &&
          created_at == o.created_at &&
          deleted_at == o.deleted_at &&
          description == o.description &&
          events == o.events &&
          failure_count == o.failure_count &&
          failure_rate == o.failure_rate &&
          http_timeout == o.http_timeout &&
          mtls_client_cert == o.mtls_client_cert &&
          name == o.name &&
          owner_id == o.owner_id &&
          period_failure_rate == o.period_failure_rate &&
          project_id == o.project_id &&
          rate_limit == o.rate_limit &&
          rate_limit_duration == o.rate_limit_duration &&
          retry_count == o.retry_count &&
          secrets == o.secrets &&
          slack_webhook_url == o.slack_webhook_url &&
          status == o.status &&
          success_count == o.success_count &&
          support_email == o.support_email &&
          uid == o.uid &&
          updated_at == o.updated_at &&
          url == o.url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [advanced_signatures, authentication, cb_state, content_type, created_at, deleted_at, description, events, failure_count, failure_rate, http_timeout, mtls_client_cert, name, owner_id, period_failure_rate, project_id, rate_limit, rate_limit_duration, retry_count, secrets, slack_webhook_url, status, success_count, support_email, uid, updated_at, url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
