=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class ModelsUpdateEndpoint < ApiModelBase
    # Convoy supports two [signature formats](https://getconvoy.io/docs/product-manual/signatures) -- simple or advanced. If left unspecified, we default to false.
    attr_accessor :advanced_signatures

    # This is used to define any custom authentication required by the endpoint. This shouldn't be needed often because webhook endpoints usually should be exposed to the internet.
    attr_accessor :authentication

    # Content type for the endpoint. Defaults to application/json if not specified.
    attr_accessor :content_type

    # Human-readable description of the endpoint. Think of this as metadata describing the endpoint
    attr_accessor :description

    # Define endpoint http timeout in seconds.
    attr_accessor :http_timeout

    # This is used to manually enable/disable the endpoint.
    attr_accessor :is_disabled

    # mTLS client certificate configuration for the endpoint
    attr_accessor :mtls_client_cert

    attr_accessor :name

    # The OwnerID is used to group more than one endpoint together to achieve [fanout](https://getconvoy.io/docs/manual/endpoints#Endpoint%20Owner%20ID)
    attr_accessor :owner_id

    # Rate limit is the total number of requests to be sent to an endpoint in the time duration specified in RateLimitDuration
    attr_accessor :rate_limit

    # Rate limit duration specifies the time range for the rate limit.
    attr_accessor :rate_limit_duration

    # Endpoint's webhook secret. If not provided, Convoy autogenerates one for the endpoint.
    attr_accessor :secret

    # Slack webhook URL is an alternative method to support email where endpoint developers can receive failure notifications on a slack channel.
    attr_accessor :slack_webhook_url

    # Endpoint developers support email. This is used for communicating endpoint state changes. You should always turn this on when disabling endpoints are enabled.
    attr_accessor :support_email

    # URL is the endpoint's URL prefixed with https. non-https urls are currently not supported.
    attr_accessor :url

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'advanced_signatures' => :'advanced_signatures',
        :'authentication' => :'authentication',
        :'content_type' => :'content_type',
        :'description' => :'description',
        :'http_timeout' => :'http_timeout',
        :'is_disabled' => :'is_disabled',
        :'mtls_client_cert' => :'mtls_client_cert',
        :'name' => :'name',
        :'owner_id' => :'owner_id',
        :'rate_limit' => :'rate_limit',
        :'rate_limit_duration' => :'rate_limit_duration',
        :'secret' => :'secret',
        :'slack_webhook_url' => :'slack_webhook_url',
        :'support_email' => :'support_email',
        :'url' => :'url'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'advanced_signatures' => :'Boolean',
        :'authentication' => :'ModelsEndpointAuthentication',
        :'content_type' => :'String',
        :'description' => :'String',
        :'http_timeout' => :'Integer',
        :'is_disabled' => :'Boolean',
        :'mtls_client_cert' => :'ModelsMtlsClientCert',
        :'name' => :'String',
        :'owner_id' => :'String',
        :'rate_limit' => :'Integer',
        :'rate_limit_duration' => :'Integer',
        :'secret' => :'String',
        :'slack_webhook_url' => :'String',
        :'support_email' => :'String',
        :'url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::ModelsUpdateEndpoint` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::ModelsUpdateEndpoint`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'advanced_signatures')
        self.advanced_signatures = attributes[:'advanced_signatures']
      end

      if attributes.key?(:'authentication')
        self.authentication = attributes[:'authentication']
      end

      if attributes.key?(:'content_type')
        self.content_type = attributes[:'content_type']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'http_timeout')
        self.http_timeout = attributes[:'http_timeout']
      end

      if attributes.key?(:'is_disabled')
        self.is_disabled = attributes[:'is_disabled']
      end

      if attributes.key?(:'mtls_client_cert')
        self.mtls_client_cert = attributes[:'mtls_client_cert']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'owner_id')
        self.owner_id = attributes[:'owner_id']
      end

      if attributes.key?(:'rate_limit')
        self.rate_limit = attributes[:'rate_limit']
      end

      if attributes.key?(:'rate_limit_duration')
        self.rate_limit_duration = attributes[:'rate_limit_duration']
      end

      if attributes.key?(:'secret')
        self.secret = attributes[:'secret']
      end

      if attributes.key?(:'slack_webhook_url')
        self.slack_webhook_url = attributes[:'slack_webhook_url']
      end

      if attributes.key?(:'support_email')
        self.support_email = attributes[:'support_email']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          advanced_signatures == o.advanced_signatures &&
          authentication == o.authentication &&
          content_type == o.content_type &&
          description == o.description &&
          http_timeout == o.http_timeout &&
          is_disabled == o.is_disabled &&
          mtls_client_cert == o.mtls_client_cert &&
          name == o.name &&
          owner_id == o.owner_id &&
          rate_limit == o.rate_limit &&
          rate_limit_duration == o.rate_limit_duration &&
          secret == o.secret &&
          slack_webhook_url == o.slack_webhook_url &&
          support_email == o.support_email &&
          url == o.url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [advanced_signatures, authentication, content_type, description, http_timeout, is_disabled, mtls_client_cert, name, owner_id, rate_limit, rate_limit_duration, secret, slack_webhook_url, support_email, url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
