=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class ModelsEventResponse < ApiModelBase
    attr_accessor :acknowledged_at

    # Deprecated
    attr_accessor :app_id

    attr_accessor :created_at

    # Data is an arbitrary JSON value that gets sent as the body of the webhook to the endpoints
    attr_accessor :data

    attr_accessor :deleted_at

    attr_accessor :endpoint_metadata

    attr_accessor :endpoints

    attr_accessor :event_type

    attr_accessor :headers

    attr_accessor :idempotency_key

    attr_accessor :is_duplicate_event

    attr_accessor :metadata

    attr_accessor :project_id

    attr_accessor :raw

    attr_accessor :source_id

    attr_accessor :source_metadata

    attr_accessor :status

    attr_accessor :uid

    attr_accessor :updated_at

    attr_accessor :url_path

    attr_accessor :url_query_params

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'acknowledged_at' => :'acknowledged_at',
        :'app_id' => :'app_id',
        :'created_at' => :'created_at',
        :'data' => :'data',
        :'deleted_at' => :'deleted_at',
        :'endpoint_metadata' => :'endpoint_metadata',
        :'endpoints' => :'endpoints',
        :'event_type' => :'event_type',
        :'headers' => :'headers',
        :'idempotency_key' => :'idempotency_key',
        :'is_duplicate_event' => :'is_duplicate_event',
        :'metadata' => :'metadata',
        :'project_id' => :'project_id',
        :'raw' => :'raw',
        :'source_id' => :'source_id',
        :'source_metadata' => :'source_metadata',
        :'status' => :'status',
        :'uid' => :'uid',
        :'updated_at' => :'updated_at',
        :'url_path' => :'url_path',
        :'url_query_params' => :'url_query_params'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'acknowledged_at' => :'String',
        :'app_id' => :'String',
        :'created_at' => :'String',
        :'data' => :'Hash<String, Object>',
        :'deleted_at' => :'String',
        :'endpoint_metadata' => :'Array<DatastoreEndpoint>',
        :'endpoints' => :'Array<String>',
        :'event_type' => :'String',
        :'headers' => :'Hash<String, Array<String>>',
        :'idempotency_key' => :'String',
        :'is_duplicate_event' => :'Boolean',
        :'metadata' => :'String',
        :'project_id' => :'String',
        :'raw' => :'String',
        :'source_id' => :'String',
        :'source_metadata' => :'DatastoreSource',
        :'status' => :'DatastoreEventStatus',
        :'uid' => :'String',
        :'updated_at' => :'String',
        :'url_path' => :'String',
        :'url_query_params' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'acknowledged_at',
        :'data',
        :'deleted_at',
        :'headers',
        :'source_metadata',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::ModelsEventResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::ModelsEventResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'acknowledged_at')
        self.acknowledged_at = attributes[:'acknowledged_at']
      end

      if attributes.key?(:'app_id')
        self.app_id = attributes[:'app_id']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'data')
        if (value = attributes[:'data']).is_a?(Hash)
          self.data = value
        end
      end

      if attributes.key?(:'deleted_at')
        self.deleted_at = attributes[:'deleted_at']
      end

      if attributes.key?(:'endpoint_metadata')
        if (value = attributes[:'endpoint_metadata']).is_a?(Array)
          self.endpoint_metadata = value
        end
      end

      if attributes.key?(:'endpoints')
        if (value = attributes[:'endpoints']).is_a?(Array)
          self.endpoints = value
        end
      end

      if attributes.key?(:'event_type')
        self.event_type = attributes[:'event_type']
      end

      if attributes.key?(:'headers')
        if (value = attributes[:'headers']).is_a?(Hash)
          self.headers = value
        end
      end

      if attributes.key?(:'idempotency_key')
        self.idempotency_key = attributes[:'idempotency_key']
      end

      if attributes.key?(:'is_duplicate_event')
        self.is_duplicate_event = attributes[:'is_duplicate_event']
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'raw')
        self.raw = attributes[:'raw']
      end

      if attributes.key?(:'source_id')
        self.source_id = attributes[:'source_id']
      end

      if attributes.key?(:'source_metadata')
        self.source_metadata = attributes[:'source_metadata']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'uid')
        self.uid = attributes[:'uid']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'url_path')
        self.url_path = attributes[:'url_path']
      end

      if attributes.key?(:'url_query_params')
        self.url_query_params = attributes[:'url_query_params']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          acknowledged_at == o.acknowledged_at &&
          app_id == o.app_id &&
          created_at == o.created_at &&
          data == o.data &&
          deleted_at == o.deleted_at &&
          endpoint_metadata == o.endpoint_metadata &&
          endpoints == o.endpoints &&
          event_type == o.event_type &&
          headers == o.headers &&
          idempotency_key == o.idempotency_key &&
          is_duplicate_event == o.is_duplicate_event &&
          metadata == o.metadata &&
          project_id == o.project_id &&
          raw == o.raw &&
          source_id == o.source_id &&
          source_metadata == o.source_metadata &&
          status == o.status &&
          uid == o.uid &&
          updated_at == o.updated_at &&
          url_path == o.url_path &&
          url_query_params == o.url_query_params
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [acknowledged_at, app_id, created_at, data, deleted_at, endpoint_metadata, endpoints, event_type, headers, idempotency_key, is_duplicate_event, metadata, project_id, raw, source_id, source_metadata, status, uid, updated_at, url_path, url_query_params].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
