=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class ModelsCreateSubscription < ApiModelBase
    # Alert configuration
    attr_accessor :alert_config

    # Deprecated but necessary for backward compatibility
    attr_accessor :app_id

    # Delivery mode configuration
    attr_accessor :delivery_mode

    # Destination endpoint ID
    attr_accessor :endpoint_id

    # Filter configuration
    attr_accessor :filter_config

    # Convoy supports mutating your request payload using a js function. Use this field to specify a `transform` function for this purpose. See this[https://docs.getconvoy.io/product-manual/subscriptions#functions] for more
    attr_accessor :function

    # Subscription Nme
    attr_accessor :name

    # Rate limit configuration
    attr_accessor :rate_limit_config

    # Source Id
    attr_accessor :source_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'alert_config' => :'alert_config',
        :'app_id' => :'app_id',
        :'delivery_mode' => :'delivery_mode',
        :'endpoint_id' => :'endpoint_id',
        :'filter_config' => :'filter_config',
        :'function' => :'function',
        :'name' => :'name',
        :'rate_limit_config' => :'rate_limit_config',
        :'source_id' => :'source_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'alert_config' => :'ModelsAlertConfiguration',
        :'app_id' => :'String',
        :'delivery_mode' => :'DatastoreDeliveryMode',
        :'endpoint_id' => :'String',
        :'filter_config' => :'ModelsFilterConfiguration',
        :'function' => :'String',
        :'name' => :'String',
        :'rate_limit_config' => :'ModelsRateLimitConfiguration',
        :'source_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::ModelsCreateSubscription` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::ModelsCreateSubscription`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'alert_config')
        self.alert_config = attributes[:'alert_config']
      end

      if attributes.key?(:'app_id')
        self.app_id = attributes[:'app_id']
      end

      if attributes.key?(:'delivery_mode')
        self.delivery_mode = attributes[:'delivery_mode']
      end

      if attributes.key?(:'endpoint_id')
        self.endpoint_id = attributes[:'endpoint_id']
      end

      if attributes.key?(:'filter_config')
        self.filter_config = attributes[:'filter_config']
      end

      if attributes.key?(:'function')
        self.function = attributes[:'function']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'rate_limit_config')
        self.rate_limit_config = attributes[:'rate_limit_config']
      end

      if attributes.key?(:'source_id')
        self.source_id = attributes[:'source_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          alert_config == o.alert_config &&
          app_id == o.app_id &&
          delivery_mode == o.delivery_mode &&
          endpoint_id == o.endpoint_id &&
          filter_config == o.filter_config &&
          function == o.function &&
          name == o.name &&
          rate_limit_config == o.rate_limit_config &&
          source_id == o.source_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [alert_config, app_id, delivery_mode, endpoint_id, filter_config, function, name, rate_limit_config, source_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
