=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class ModelsFilterResponse < ApiModelBase
    attr_accessor :body

    attr_accessor :enabled_at

    attr_accessor :event_type

    attr_accessor :headers

    attr_accessor :path

    attr_accessor :query

    attr_accessor :raw_body

    attr_accessor :raw_headers

    attr_accessor :raw_path

    attr_accessor :raw_query

    attr_accessor :subscription_id

    attr_accessor :uid

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'body' => :'body',
        :'enabled_at' => :'enabled_at',
        :'event_type' => :'event_type',
        :'headers' => :'headers',
        :'path' => :'path',
        :'query' => :'query',
        :'raw_body' => :'raw_body',
        :'raw_headers' => :'raw_headers',
        :'raw_path' => :'raw_path',
        :'raw_query' => :'raw_query',
        :'subscription_id' => :'subscription_id',
        :'uid' => :'uid'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'body' => :'Hash<String, Object>',
        :'enabled_at' => :'String',
        :'event_type' => :'String',
        :'headers' => :'Hash<String, Object>',
        :'path' => :'Hash<String, Object>',
        :'query' => :'Hash<String, Object>',
        :'raw_body' => :'Hash<String, Object>',
        :'raw_headers' => :'Hash<String, Object>',
        :'raw_path' => :'Hash<String, Object>',
        :'raw_query' => :'Hash<String, Object>',
        :'subscription_id' => :'String',
        :'uid' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::ModelsFilterResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::ModelsFilterResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'body')
        if (value = attributes[:'body']).is_a?(Hash)
          self.body = value
        end
      end

      if attributes.key?(:'enabled_at')
        self.enabled_at = attributes[:'enabled_at']
      end

      if attributes.key?(:'event_type')
        self.event_type = attributes[:'event_type']
      end

      if attributes.key?(:'headers')
        if (value = attributes[:'headers']).is_a?(Hash)
          self.headers = value
        end
      end

      if attributes.key?(:'path')
        if (value = attributes[:'path']).is_a?(Hash)
          self.path = value
        end
      end

      if attributes.key?(:'query')
        if (value = attributes[:'query']).is_a?(Hash)
          self.query = value
        end
      end

      if attributes.key?(:'raw_body')
        if (value = attributes[:'raw_body']).is_a?(Hash)
          self.raw_body = value
        end
      end

      if attributes.key?(:'raw_headers')
        if (value = attributes[:'raw_headers']).is_a?(Hash)
          self.raw_headers = value
        end
      end

      if attributes.key?(:'raw_path')
        if (value = attributes[:'raw_path']).is_a?(Hash)
          self.raw_path = value
        end
      end

      if attributes.key?(:'raw_query')
        if (value = attributes[:'raw_query']).is_a?(Hash)
          self.raw_query = value
        end
      end

      if attributes.key?(:'subscription_id')
        self.subscription_id = attributes[:'subscription_id']
      end

      if attributes.key?(:'uid')
        self.uid = attributes[:'uid']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          body == o.body &&
          enabled_at == o.enabled_at &&
          event_type == o.event_type &&
          headers == o.headers &&
          path == o.path &&
          query == o.query &&
          raw_body == o.raw_body &&
          raw_headers == o.raw_headers &&
          raw_path == o.raw_path &&
          raw_query == o.raw_query &&
          subscription_id == o.subscription_id &&
          uid == o.uid
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [body, enabled_at, event_type, headers, path, query, raw_body, raw_headers, raw_path, raw_query, subscription_id, uid].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
