=begin
#Convoy API Reference

#Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.

The version of the OpenAPI document: 26.3.5
Contact: support@getconvoy.io
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ConvoyApi
  class ModelsSubscriptionResponse < ApiModelBase
    # subscription config
    attr_accessor :alert_config

    attr_accessor :created_at

    attr_accessor :deleted_at

    attr_accessor :delivery_mode

    attr_accessor :device_metadata

    attr_accessor :endpoint_metadata

    attr_accessor :filter_config

    attr_accessor :function

    attr_accessor :name

    attr_accessor :project_id

    attr_accessor :rate_limit_config

    attr_accessor :retry_config

    attr_accessor :source_metadata

    attr_accessor :type

    attr_accessor :uid

    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'alert_config' => :'alert_config',
        :'created_at' => :'created_at',
        :'deleted_at' => :'deleted_at',
        :'delivery_mode' => :'delivery_mode',
        :'device_metadata' => :'device_metadata',
        :'endpoint_metadata' => :'endpoint_metadata',
        :'filter_config' => :'filter_config',
        :'function' => :'function',
        :'name' => :'name',
        :'project_id' => :'project_id',
        :'rate_limit_config' => :'rate_limit_config',
        :'retry_config' => :'retry_config',
        :'source_metadata' => :'source_metadata',
        :'type' => :'type',
        :'uid' => :'uid',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'alert_config' => :'DatastoreAlertConfiguration',
        :'created_at' => :'String',
        :'deleted_at' => :'String',
        :'delivery_mode' => :'DatastoreDeliveryMode',
        :'device_metadata' => :'DatastoreDevice',
        :'endpoint_metadata' => :'DatastoreEndpoint',
        :'filter_config' => :'DatastoreFilterConfiguration',
        :'function' => :'String',
        :'name' => :'String',
        :'project_id' => :'String',
        :'rate_limit_config' => :'DatastoreRateLimitConfiguration',
        :'retry_config' => :'DatastoreRetryConfiguration',
        :'source_metadata' => :'DatastoreSource',
        :'type' => :'DatastoreSubscriptionType',
        :'uid' => :'String',
        :'updated_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'alert_config',
        :'deleted_at',
        :'device_metadata',
        :'endpoint_metadata',
        :'filter_config',
        :'function',
        :'rate_limit_config',
        :'retry_config',
        :'source_metadata',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConvoyApi::ModelsSubscriptionResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConvoyApi::ModelsSubscriptionResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'alert_config')
        self.alert_config = attributes[:'alert_config']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'deleted_at')
        self.deleted_at = attributes[:'deleted_at']
      end

      if attributes.key?(:'delivery_mode')
        self.delivery_mode = attributes[:'delivery_mode']
      end

      if attributes.key?(:'device_metadata')
        self.device_metadata = attributes[:'device_metadata']
      end

      if attributes.key?(:'endpoint_metadata')
        self.endpoint_metadata = attributes[:'endpoint_metadata']
      end

      if attributes.key?(:'filter_config')
        self.filter_config = attributes[:'filter_config']
      end

      if attributes.key?(:'function')
        self.function = attributes[:'function']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'rate_limit_config')
        self.rate_limit_config = attributes[:'rate_limit_config']
      end

      if attributes.key?(:'retry_config')
        self.retry_config = attributes[:'retry_config']
      end

      if attributes.key?(:'source_metadata')
        self.source_metadata = attributes[:'source_metadata']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'uid')
        self.uid = attributes[:'uid']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          alert_config == o.alert_config &&
          created_at == o.created_at &&
          deleted_at == o.deleted_at &&
          delivery_mode == o.delivery_mode &&
          device_metadata == o.device_metadata &&
          endpoint_metadata == o.endpoint_metadata &&
          filter_config == o.filter_config &&
          function == o.function &&
          name == o.name &&
          project_id == o.project_id &&
          rate_limit_config == o.rate_limit_config &&
          retry_config == o.retry_config &&
          source_metadata == o.source_metadata &&
          type == o.type &&
          uid == o.uid &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [alert_config, created_at, deleted_at, delivery_mode, device_metadata, endpoint_metadata, filter_config, function, name, project_id, rate_limit_config, retry_config, source_metadata, type, uid, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
